# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalogo.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'catalogo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61talogo.proto\"%\n\x15\x43onsulta_nome_request\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\'\n\x16\x43onsulta_preco_request\x12\r\n\x05valor\x18\x01 \x01(\x02\"=\n\x19\x41tualizar_estoque_request\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\":\n\x07Produto\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x02\x12\x12\n\nquantidade\x18\x03 \x01(\x05\"-\n\x10Produto_response\x12\x19\n\x07produto\x18\x01 \x01(\x0b\x32\x08.Produto\"5\n\x17Lista_produtos_response\x12\x1a\n\x08produtos\x18\x01 \x03(\x0b\x32\x08.Produto\".\n\x1a\x41tualizar_estoque_response\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xf3\x01\n\x0e\x43\x61tlogoService\x12@\n\x13\x43onsultlar_por_nome\x12\x16.Consulta_nome_request\x1a\x11.Produto_response\x12Q\n\x1c\x43onsultar_por_preco_inferior\x12\x17.Consulta_preco_request\x1a\x18.Lista_produtos_response\x12L\n\x11\x41tualizar_estoque\x12\x1a.Atualizar_estoque_request\x1a\x1b.Atualizar_estoque_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTA_NOME_REQUEST']._serialized_start=18
  _globals['_CONSULTA_NOME_REQUEST']._serialized_end=55
  _globals['_CONSULTA_PRECO_REQUEST']._serialized_start=57
  _globals['_CONSULTA_PRECO_REQUEST']._serialized_end=96
  _globals['_ATUALIZAR_ESTOQUE_REQUEST']._serialized_start=98
  _globals['_ATUALIZAR_ESTOQUE_REQUEST']._serialized_end=159
  _globals['_PRODUTO']._serialized_start=161
  _globals['_PRODUTO']._serialized_end=219
  _globals['_PRODUTO_RESPONSE']._serialized_start=221
  _globals['_PRODUTO_RESPONSE']._serialized_end=266
  _globals['_LISTA_PRODUTOS_RESPONSE']._serialized_start=268
  _globals['_LISTA_PRODUTOS_RESPONSE']._serialized_end=321
  _globals['_ATUALIZAR_ESTOQUE_RESPONSE']._serialized_start=323
  _globals['_ATUALIZAR_ESTOQUE_RESPONSE']._serialized_end=369
  _globals['_CATLOGOSERVICE']._serialized_start=372
  _globals['_CATLOGOSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
