# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC.catalogo_pb2 as catalogo__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatlogoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Consultlar_por_nome = channel.unary_unary(
                '/CatlogoService/Consultlar_por_nome',
                request_serializer=catalogo__pb2.Consulta_nome_request.SerializeToString,
                response_deserializer=catalogo__pb2.Produto_response.FromString,
                _registered_method=True)
        self.Consultar_por_preco_inferior = channel.unary_unary(
                '/CatlogoService/Consultar_por_preco_inferior',
                request_serializer=catalogo__pb2.Consulta_preco_request.SerializeToString,
                response_deserializer=catalogo__pb2.Lista_produtos_response.FromString,
                _registered_method=True)
        self.Atualizar_estoque = channel.unary_unary(
                '/CatlogoService/Atualizar_estoque',
                request_serializer=catalogo__pb2.Atualizar_estoque_request.SerializeToString,
                response_deserializer=catalogo__pb2.Atualizar_estoque_response.FromString,
                _registered_method=True)


class CatlogoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Consultlar_por_nome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consultar_por_preco_inferior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Atualizar_estoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatlogoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Consultlar_por_nome': grpc.unary_unary_rpc_method_handler(
                    servicer.Consultlar_por_nome,
                    request_deserializer=catalogo__pb2.Consulta_nome_request.FromString,
                    response_serializer=catalogo__pb2.Produto_response.SerializeToString,
            ),
            'Consultar_por_preco_inferior': grpc.unary_unary_rpc_method_handler(
                    servicer.Consultar_por_preco_inferior,
                    request_deserializer=catalogo__pb2.Consulta_preco_request.FromString,
                    response_serializer=catalogo__pb2.Lista_produtos_response.SerializeToString,
            ),
            'Atualizar_estoque': grpc.unary_unary_rpc_method_handler(
                    servicer.Atualizar_estoque,
                    request_deserializer=catalogo__pb2.Atualizar_estoque_request.FromString,
                    response_serializer=catalogo__pb2.Atualizar_estoque_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CatlogoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CatlogoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatlogoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Consultlar_por_nome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatlogoService/Consultlar_por_nome',
            catalogo__pb2.Consulta_nome_request.SerializeToString,
            catalogo__pb2.Produto_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consultar_por_preco_inferior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatlogoService/Consultar_por_preco_inferior',
            catalogo__pb2.Consulta_preco_request.SerializeToString,
            catalogo__pb2.Lista_produtos_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Atualizar_estoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatlogoService/Atualizar_estoque',
            catalogo__pb2.Atualizar_estoque_request.SerializeToString,
            catalogo__pb2.Atualizar_estoque_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
